---
title: "yas_queen"
author: "Nathaniel Richardson"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(dplyr)
require(ggplot2)
```

```{r}
N<-1000
```

```{r}
X <- c(1:N)
Y <- -(X^3)+(1000*X^2)+20000000*rnorm(N)
Y <- Y

df<- data_frame(
X,
Y
)
```

```{r}
ggplot(data = df, aes(x = X, y = Y))+
  geom_point()
```

```{r}
OLS<- function(Y, Y_hat) t(Y - Y_hat)%*%(Y - Y_hat)

R2 <- function(Y, Y_hat) 1 - apply((Y - Y_hat)^2, 1, sum)  / apply((apply(Y - Y_hat, 1, mean)**2), 1, sum)

sigmoid <- function(H) 1/(1+exp(-H))

feed_forward <- function(X, W1, b1,W2,b2,W3, b3,W4,b4,W5, b5) {
    Z1 <- sigmoid((X%*%W1) +b1)
    Z2 <- sigmoid((Z1%*%W2)+b2)
    Z3 <- sigmoid((Z2%*%W3)+b3)
    Z4 <- sigmoid((Z3%*%W4)+b4)
    y_hat <- ((Z4%*%W5)+b5)
    return(list(Z1,Z2,Z3,Z4,y_hat))
}
```



```{r}
D = 1
M1 = 4
M2 = 4
M3 = 4
M4 = 4
K = 1

W1 = t(replicate(D, rnorm(M1)))
b1 = rnorm(M1)
W2 = t(replicate(M1, rnorm(M2)))
b2 = rnorm(M2)
W3 = t(replicate(M2, rnorm(M3)))
b3 = rnorm(M3)
W4 = t(replicate(M3, rnorm(M4)))
b4 = rnorm(M4)
W5 = replicate(M4, rnorm(K))
b5 = rnorm(K)
```

```{r}
W5
```




```{r}
J = c()
eta = 3e-7
epochs = 5e4
en = c()


for (i in 1:epochs){
    l <- feed_forward(X, W1, b1,W2,b2,W3, b3,W4,b4,W5, b5)
    Z1 <- l[[1]]
    Z2 <- l[[2]]
    Z3 <- l[[3]]
    Z4<-  l[[4]]
  
    Y_hat <- l[[5]]
    J[i] <- OLS(Y,Y_hat)
    
    dH5 = as.matrix(Y_hat-Y)
    dW5 = t(Z4)%*% dH5
    W5  = W5- eta*dW5
    b5  = b5- eta* apply(dH5, 1, sum)
    
    dZ4 = dH5 %*% t(W5)
    dH4 = dZ4*Z4 * (1-Z4)
    dW4 = t(Z3) %*% dH4
    W4  = W4 - eta*dW4
    b4 = b4 - eta* apply(dH4, 1, sum)
    
    dZ3 = dH4 %*% t(W4)
    dH3 = dZ3*Z3 * (1-Z3)
    dW3 = t(Z2) %*% dH3
    W3  = W3 - eta*dW3
    b3 = b3 - eta* apply(dH3, 1, sum)
    
    dZ2 = dH3 %*% t(W3)
    dH2 = dZ2*Z2 * (1-Z2)
    dW2 = t(Z2) %*% dH2
    W2  = W2 - eta*dW2
    b2 = b2 - eta* apply(dH2, 1, sum)
    
    dZ1 = dH2%*%t(W2)
    dH1 = dZ3*Z1 * (1-Z1)
    dW1 = t(X) %*% dH1
    W1 = W1- eta* dW1
    b1 = b1- eta*apply(dH1,1, sum) 
    
    en[i] <- i
    
    if (i%%1000==0){
        print (i)
    }
}
```

```{r}
plot(en, J)
```

```{r}
ggplot(data = df, aes(x = X, y = Y))+
  geom_point()+
  geom_line(y = Y_hat, color = "blue")
```

```{r}
R <- R2(Y, Y_hat)

```

